[package]
name = "negotiation"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
snow = "0.10"
security = { path = "../security" }
common  = {path = "../common" }
